services:
  app:
    build: .
    image: khoalamphilong/vietnamese-stt-server:latest
    ports:
      - "8000:8000"
    environment:
      - MODEL_DIR=/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
